---
abstract: 'Determine the infinitive form of a conjugated word'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-EN-Infinitive
provides:
  Lingua::EN::Infinitive:
    file: lib/Lingua/EN/Infinitive.pm
    version: '1.12'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '1.12'
